"""add reservation sms tracking

Revision ID: 23abf90f7f44
Revises: f708a0a9b986
Create Date: 2026-08-29 02:19:21.040047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23abf90f7f44'
down_revision: Union[str, Sequence[str], None] = 'f708a0a9b986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('client_confirmation_sms_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'client_confirmation_sms_sent_at')
    # ### end Alembic commands ###
