"""add reservation hold expiration

Revision ID: 9a63596a5f04
Revises: 377ae2b515ac
Create Date: 2026-08-14 17:51:08.301247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a63596a5f04'
down_revision: Union[str, Sequence[str], None] = '377ae2b515ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('hold_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'hold_expires_at')
    # ### end Alembic commands ###
