"""production otp farazsms integration

Revision ID: f708a0a9b986
Revises: 87fd02a13d40
Create Date: 2026-08-28 01:05:15.560474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f708a0a9b986'
down_revision: Union[str, Sequence[str], None] = '87fd02a13d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_verification', sa.Column('reservation_id', sa.Integer(), nullable=False))
    op.add_column('phone_verification', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('phone_verification', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('phone_verification', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('phone_verification', sa.Column('provider', sa.String(length=30), nullable=False))
    op.add_column('phone_verification', sa.Column('provider_message_id', sa.String(length=255), nullable=True))
    op.add_column('phone_verification', sa.Column('failure_reason', sa.String(length=500), nullable=True))
    op.add_column('phone_verification', sa.Column('request_ip', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_phone_verification_created_at'), 'phone_verification', ['created_at'], unique=False)
    op.create_index(op.f('ix_phone_verification_expires_at'), 'phone_verification', ['expires_at'], unique=False)
    op.create_index(op.f('ix_phone_verification_request_ip'), 'phone_verification', ['request_ip'], unique=False)
    op.create_index(op.f('ix_phone_verification_reservation_id'), 'phone_verification', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_phone_verification_status'), 'phone_verification', ['status'], unique=False)
    op.create_foreign_key(None, 'phone_verification', 'reservation', ['reservation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('phone_verification', 'hold_expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_verification', sa.Column('hold_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'phone_verification', type_='foreignkey')
    op.drop_index(op.f('ix_phone_verification_status'), table_name='phone_verification')
    op.drop_index(op.f('ix_phone_verification_reservation_id'), table_name='phone_verification')
    op.drop_index(op.f('ix_phone_verification_request_ip'), table_name='phone_verification')
    op.drop_index(op.f('ix_phone_verification_expires_at'), table_name='phone_verification')
    op.drop_index(op.f('ix_phone_verification_created_at'), table_name='phone_verification')
    op.drop_column('phone_verification', 'request_ip')
    op.drop_column('phone_verification', 'failure_reason')
    op.drop_column('phone_verification', 'provider_message_id')
    op.drop_column('phone_verification', 'provider')
    op.drop_column('phone_verification', 'status')
    op.drop_column('phone_verification', 'sent_at')
    op.drop_column('phone_verification', 'created_at')
    op.drop_column('phone_verification', 'reservation_id')
    # ### end Alembic commands ###
